# [Required] Enables TLS 
tls: true
# [Required] Sets listening port
port: 8443
# [Required in case 'tls' is true] TLS certificate path
# NB! Path must be relative to THIS configuration file
tlsCertPath: tls.crt
# [Required in case 'tls' is true] TLS key path
# NB! Path must be relative to THIS configuration file
tlsKeyPath: tls.key
